# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f27c8d118ef0eea95480c031ea1b24d4"
application_url = "https://edna-fork--development.gadget.app/api/shopify/install-or-render"
embedded = true
  name = "ednav1-1"
  handle = "ednav1-1"

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [
  "https://edna-fork--development.gadget.app/api/connections/auth/shopify/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
