# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ednav1-1"
client_id = "f27c8d118ef0eea95480c031ea1b24d4"
application_url = "https://edna-fork--development.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = [
  "https://edna-fork--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false

[build]
include_config_on_deploy = true

[[extensions]]
type = "theme_app_extension"
name = "Gadget chatbot"
handle = "chatbot"

[[extensions]]
type = "theme_app_extension"
name = "Bundle Discounts"
handle = "bundle-display"